// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKuTIbcMoDDD8JStvUscfPcZfIH65ug-o',
    appId: '1:703543264986:web:29a9ec39818706114107e3',
    messagingSenderId: '703543264986',
    projectId: 'e---commerce-655f0',
    authDomain: 'e---commerce-655f0.firebaseapp.com',
    storageBucket: 'e---commerce-655f0.firebasestorage.app',
    measurementId: 'G-J49FYRZL0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfIs2YDzjxCgGscxDuEvpK-WnOIYovcX4',
    appId: '1:703543264986:android:486e4ce4608f3ad34107e3',
    messagingSenderId: '703543264986',
    projectId: 'e---commerce-655f0',
    storageBucket: 'e---commerce-655f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeefUX_h8yIKoKrjq20fZODgg_HAelCM',
    appId: '1:703543264986:ios:e8f4bb2012bb92524107e3',
    messagingSenderId: '703543264986',
    projectId: 'e---commerce-655f0',
    storageBucket: 'e---commerce-655f0.firebasestorage.app',
    iosClientId: '703543264986-s8h2fbqp46vr2lt8lfrt5adrmlhbksvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolcOnlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpeefUX_h8yIKoKrjq20fZODgg_HAelCM',
    appId: '1:703543264986:ios:e8f4bb2012bb92524107e3',
    messagingSenderId: '703543264986',
    projectId: 'e---commerce-655f0',
    storageBucket: 'e---commerce-655f0.firebasestorage.app',
    iosClientId: '703543264986-s8h2fbqp46vr2lt8lfrt5adrmlhbksvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolcOnlineShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKuTIbcMoDDD8JStvUscfPcZfIH65ug-o',
    appId: '1:703543264986:web:88d7290972ea52364107e3',
    messagingSenderId: '703543264986',
    projectId: 'e---commerce-655f0',
    authDomain: 'e---commerce-655f0.firebaseapp.com',
    storageBucket: 'e---commerce-655f0.firebasestorage.app',
    measurementId: 'G-FM0YY0W2WG',
  );

}